# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'pv-prod-azdevops'
    azureResourceGroup: 'pv-prod-aks-rg'
    kubernetesCluster: 'pv-aks-prod-01'
    namespace: 'loki'
    command: 'login'
    outputFormat: 'none'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      prom_pod=($(kubectl get pods -n loki | grep promtail | awk '{print $1}'))
      for po in ${prom_pod[@]}; do 
          echo ">>>>>>>>> $po"
          kubectl exec -t -n loki $po -- du -hs /mnt
      done