# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest


variables:
  azureSubscriptionEndpoint: pv-prod-azdevops
  azureContainerRegistry: pvbackend.azurecr.io
  azureResourceGroup: pv-prod-aks-rg
  kubernetesCluster: pv-aks-prod-01

steps:
- task: Kubernetes@1
  displayName: kubectl get
  inputs:
    connectionType: Azure Resource Manager
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureResourceGroup: $(azureResourceGroup)
    kubernetesCluster: $(kubernetesCluster)
    command: get
    arguments: pods -n loki| grep promtail
